/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tst.obs;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.springframework.boot.test.context.SpringBootTest;
import tst.obs.App;

@SpringBootTest
class AppTest {

    @Test
    void context_should_load() {}
}
