services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1-amd64
    environment:
      discovery.type: single-node
      ELASTIC_PASSWORD: elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1-amd64
    ports:
      - 5601:5601