:PROPERTIES:
:header-args: :results silent
:END:
#+title: Prototype: Observability with Elastic
#+author: Aaron Kunde
This is a prototype for an example setup to accomplish [[https://en.wikipedia.org/wiki/Observability_(software)][observability]] with the [[https://www.elastic.co/][Elastic Stack]].

There is no unique definition of observability, but it always relies on metrics, logs and traces.

Therefore the example setup
1. writes logs using [[https://www.elastic.co/guide/en/ecs-logging/overview/current/intro.html][ECS logging]]
2. collects metrics using [[https://www.elastic.co/beats/metricbeat][Metricbeat]] and [[https://www.elastic.co/de/observability/application-performance-monitoring][APM]],
3. collects logs using [[https://www.elastic.co/de/beats/filebeat][Filebeat]],
4. collects traces with APM on client and server side,
5. collects metrics and traces with [[https://opentelemetry.io/][OpenTelemetry]] on client side.

For testing, some example Java and Go applications are used:
- Using different instrumentation methods from [[https://opentelemetry.io/][OpenTelemetry]] and [[https://www.elastic.co/de/observability][Elastic Observability]].
- Testing tracing with REST-Calls and asynchronous [[https://cloudevents.io/][CloudEvents]] on [[https://kafka.apache.org/][Apache Kafka]].

* Build applications
#+begin_src shell
  gradle build -p apps && \
  podman-compose build
#+end_src

* Start
1. To run the example, type:
#+begin_src shell
  podman-compose up -d
#+end_src

2. Verify, indices exists, running:
#+begin_src shell
  podman-compose exec elasticsearch curl -uelastic:elastic localhost:9200/_cat/indices
#+end_src

Should return something like:
#+begin_example
  yellow open .ds-metrics-apm.app.my_cool_service-default-2023.12.18-000001    GIk4rOWUSW-83Dux8P-9QA 1 1 1077 0 621.8kb 621.8kb 621.8kb
  green  open .internal.alerts-observability.logs.alerts-default-000001        XprZtj8URBOKYokJ8v4Zjw 1 0    0 0    249b    249b    249b
  yellow open .ds-filebeat-8.11.1-2023.12.18-000001                            5VmMauFFSrO192oG_CTEqg 1 1   52 0  59.7kb  59.7kb  59.7kb
  yellow open .ds-metrics-apm.transaction.1m-default-2023.12.18-000001         -5Zfd60ASwqyutDbsFbpTA 1 1   32 0 151.3kb 151.3kb 151.3kb
  green  open .internal.alerts-observability.uptime.alerts-default-000001      lMEZ9gBeSlm1-eZD9DDmuQ 1 0    0 0    249b    249b    249b
  green  open .internal.alerts-ml.anomaly-detection.alerts-default-000001      A3SZoEHTQbmMvu0yrsGQpA 1 0    0 0    249b    249b    249b
  yellow open .ds-metricbeat-8.11.1-2023.12.18-000001                          Qg4S8pyqRjm_n_9zFhMiLQ 1 1 4831 0   4.6mb   4.6mb   4.6mb
  green  open .internal.alerts-observability.slo.alerts-default-000001         aUhRYcySTVG4xvFgDYIxyQ 1 0    0 0    249b    249b    249b
  green  open .internal.alerts-observability.apm.alerts-default-000001         ybVpTm89Qvu-WkOggqxhZQ 1 0    0 0    249b    249b    249b
  green  open .internal.alerts-observability.metrics.alerts-default-000001     znDAc5kTT2eBhxev-SSb1g 1 0    0 0    249b    249b    249b
  green  open .kibana-observability-ai-assistant-conversations-000001          hOoMHEwRTzO9II4W2NSorw 1 0    0 0    249b    249b    249b
  yellow open .ds-traces-apm-default-2023.12.18-000001                         dO7NwXXjSjqDODOznEa78A 1 1  100 0 585.5kb 585.5kb 585.5kb
  yellow open .ds-metrics-apm.internal-default-2023.12.18-000001               9VmoxBqSTyyvAy_0Wa4yxA 1 1  442 0 389.1kb 389.1kb 389.1kb
  green  open .internal.alerts-observability.threshold.alerts-default-000001   53dnDJcgTFeUvwuAJywXag 1 0    0 0    249b    249b    249b
  green  open .kibana-observability-ai-assistant-kb-000001                     Ito5c5g7SWCC2tcaeG4C9A 1 0    0 0    249b    249b    249b
  yellow open .ds-metrics-apm.service_summary.1m-default-2023.12.18-000001     ShfRjk3oTIKNFZCR9nttyA 1 1   32 0  71.2kb  71.2kb  71.2kb
  green  open .internal.alerts-security.alerts-default-000001                  _bwsTDaURZG-gXeD_IUrag 1 0    0 0    249b    249b    249b
  yellow open .ds-metrics-apm.app.apm_server-default-2023.12.18-000001         0zg6IPGnSWmCGV44MrN-RA 1 1   52 0  86.6kb  86.6kb  86.6kb
  yellow open .ds-metrics-apm.service_transaction.1m-default-2023.12.18-000001 iujgNMNVTPGWA1FTD3gZfg 1 1   32 0  93.3kb  93.3kb  93.3kb
  green  open .internal.alerts-stack.alerts-default-000001                     lXiMpOJgTfKy5gUQGK9mlg 1 0    0 0    249b    249b    249b
#+end_example

Logs and metrics should be visible in Kibana: [[http://localhost:5601/app/observability/overview][Kibana]] after authentication with:
- Username: /elastic/
- Passord: /elastic/

* Setup
** Elasticsearch
The setup is based on [[https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html][Install Elasticsearch with Docker]] and is a simplified version of the [[https://github.com/elastic/elasticsearch/blob/8.11/docs/reference/setup/install/docker/docker-compose.yml][docker-compose]] example:
- [[https://www.elastic.co/guide/en/elasticsearch/reference/8.11/security-minimal-setup.html][Minimal security]] to use [[* APM][APM]]
- No persistence
- Use only one single node

** Kibana
The setup is based on [[https://www.elastic.co/guide/en/kibana/current/docker.html][Install Kibana with Docker]] and a simplified version of the [[https://github.com/elastic/elasticsearch/blob/8.11/docs/reference/setup/install/docker/docker-compose.yml][docker-compose]] example:
- [[https://www.elastic.co/guide/en/elasticsearch/reference/8.11/security-minimal-setup.html][Minimal security]] to use [[* APM][APM]]
- No persistence
- Setting of ~xpack.encryptedSavedObjects.encryptionKey~ to avoid loosing functionality, described in [[https://www.elastic.co/guide/en/kibana/current/xpack-security-secure-saved-objects.html][Secure saved objects]].
- Setting of ~xpack.fleet.packages~ to enable [[* APM][APM]]-App on startup.
- Settings are set using [[https://www.elastic.co/guide/en/kibana/7.17/docker.html#environment-variable-config][environment variables]].
- Kibana can be access using the URL: http://localhost:5601/

** Filebeat
The setup is based on [[https://www.elastic.co/guide/en/beats/filebeat/current/running-on-docker.html][Run Filebeat on Docker]] with the following adjustments:
- Not using a volume-mounted ~filebeat.yml~
- Since Filebeat [[https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover.html][Autodiscover]] does not support Podman, log files are shared, using volumes

** Metricbeat
The setup is based on [[https://www.elastic.co/guide/en/beats/metricbeat/current/running-on-docker.html][Run Metricbeat on Docker]] with the following adjustments:
- Not using a volume-mounted ~metricbeat.yml~
- Since Metricbeat [[https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-autodiscover.html][Autodiscover]] does not support Podman, metric sources are configured individually
- Try to get metrics from App1, using [[https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-http.html][HTTP module]]. Data is accessible in Kibana in the Metrics Explorer by ~http.app1.names~
- Collect metrics from App2, using [[https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-prometheus.html][Prometheus module]].
- Added some tags and fields for experimenting. These costs more resources!

** APM
The setup is based on [[https://www.elastic.co/guide/en/apm/guide/current/running-on-docker.html][Run APM Server on Docker]] with the following adjustments:
- Not using a volume-mounted ~apm-server.yml~
- For APM functions properly, Elastic security must be enabled on a minimum scale.

** Kafka
Based on [[https://github.com/bitnami/containers/blob/main/bitnami/kafka/3.5/debian-11/docker-compose.yml][Bitnami Containers]] with some adjustments:
- No persistence
- Added an additional external listener to get local development and AKHQ running (see: https://github.com/tchiotludo/akhq/issues/1085). This means:
  - Kafka is external accessible using ~localhost:9092~
  - and internal accessible using ~kafka:9094~

** AKHQ
[[https://akhq.io/][AKHQ]] is used to have an UI for inspecting and creating messages in Kafka. The configuration is based on [[https://akhq.io/docs/configuration/docker.html][official Documentation]], but without using an external file. The UI can be accessed by [[http://localhost:9080]].

** MySQL
[[https://www.mysql.com][MySQL]] is used as an example database for persistence.

** PostgreSQL
[[https://www.postgresql.org][PostgreSQL]] is used as another example database for persistence.

** Example Applications
The following applications describe different setups and scenarios:
|      | Implementation   | Logging | Logging-Format | Metrics                           | Observability       |
|------+------------------+---------+----------------+-----------------------------------+---------------------|
| App1 | Java Spring Boot | Logback | raw            | Spring Actuator JSON              | APM Agent           |
| App2 | Java Spring Boot | Logback | ECS Logging    | Spring Actuator JSON + Prometheus | APM Agent           |
| App3 | Java Spring Boot | Logback | ECS Logging    | Spring Actuator JSON              | OpenTelemetry Agent |
| App4 | Go               | Logrus  | ECS Logging    | Prometheus                        | Opentelemetry       |
Each application is deployed as a variant either connected to a MySQL or PostgreSQL database.

*** App1
A simple Spring-Boot application:
- Writes logs to shared volume, so that filebeat can access them
- Uses default [[https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.metrics.export.simple][simple exporter]] to populate [[https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html][Spring Boot Actuator]] default metrics over HTTP
- Application-Logs are sent to elastic by filebeat
- Instrumented, using the [[https://www.elastic.co/guide/en/apm/agent/java/1.x/intro.html][APM Java Agent]]
- Has custom metrics, which count the API-calls
- Writes messages to Kafka topic ~topic1~
- Reads messages from Kafka topics ~topic2~ and ~topic3~

**** APIs
***** Success
The following call writes a message to Kafka topic ~topic1~:
#+begin_src shell
  curl localhost:8181/api-1
#+end_src

***** Throwing unexpected errors / Stacktrace
#+begin_src shell
  curl localhost:8181/api-2
#+end_src

**** Metrics
Metrics are only available at the actuator endpoint, e.g. for the ~api1Counter~:
#+begin_src shell :results replace raw :wrap src json
   curl localhost:8181/actuator/metrics/app1m.api-1.counter
#+end_src

The output will be something like:
#+begin_src json
{"name":"app1m.api-1.counter","measurements":[{"statistic":"COUNT","value":0.0}],"availableTags":[{"tag":"type","values":["FACHLICH"]},{"tag":"it-1","values":["it-2"]}]}
#+end_src

Since these metrics cannot be requested by a single URL, they can't be collected with Metricbeat. They are accessible by APM.

**** Traces
Setting the the [[https://www.w3.org/TR/trace-context/][W3C Trace Context]]:
#+begin_src shell
  curl -H 'traceparent: 00-01010000000000000000000000000001-0000000000000001-01' localhost:8181/api-1
#+end_src

In Kibana ~trace.id~ and ~trace.parent~ can be verified at /Observability/ -> /APM/ -> /Services/ -> /app1/ -> /Transactions/ -> /AppRestController#app1/:
#+begin_example
  ...
  http
  http.request.headers.Traceparent 00-01010000000000000000000000000001-0000000000000001-01
  ...
  parent
  parent.id 0000000000000001
  ...
  span
  span.id 694c633dcd107af3
  ...
  trace
  trace.id 01010000000000000000000000000001
  ...
#+end_example
Traces and spans are even possible with Kafka topcis on the consumer site, because these W3C-headers are also set as Kafka headers
- traceparent :: Like the W3C-Header. E.g. ~00-01010000000000000000000000000001-7226b7e159fb2a61-01~
- elasticapmtraceparent :: Some specific header for Elastic. E.g. ~1103806595072~
- tracestate :: An optional W3C-Header. Not always set. E.g. ~es=s:1~

**** Logs
The following fields are set in the log messages:
| Field              | Value                                                                                                                         |
|--------------------+-------------------------------------------------------------------------------------------------------------------------------|
| _id                | q6h865EBkJCAMLR0FlbY                                                                                                          |
| _index             | .ds-filebeat-8.11.1-2024.09.13-000001                                                                                         |
| _score             | -                                                                                                                             |
| @timestamp         | Sep 13, 2024 @ 15:04:22.759                                                                                                   |
| agent.ephemeral_id | 92dc00d5-4364-429a-9894-e33011187cb3                                                                                          |
| agent.hostname     | 5b73a6bd3b99                                                                                                                  |
| agent.id           | a0f97589-8208-4933-9389-c32bf0f7b2d1                                                                                          |
| agent.name         | 5b73a6bd3b99                                                                                                                  |
| agent.type         | filebeat                                                                                                                      |
| agent.version      | 8.11.1                                                                                                                        |
| ecs.version        | 8.0.0                                                                                                                         |
| host.name          | 5b73a6bd3b99                                                                                                                  |
| input.type         | filestream                                                                                                                    |
| log.file.device_id | 2080                                                                                                                          |
| log.file.inode     | 6727840                                                                                                                       |
| log.file.path      | /var/log/app_logs/app1m.log                                                                                                   |
| log.offset         | 63,351                                                                                                                        |
| message            | 2024-09-13T13:04:16.916Z  INFO 1 --- [app1m] [http-nio-8081-exec-10] pt.obs.rest.AppRestController            : Calling API 1 |

#+begin_src json
  {
    "_index": ".ds-filebeat-8.11.1-2024.09.13-000001",
    "_id": "q6h865EBkJCAMLR0FlbY",
    "_version": 1,
    "_score": 0,
    "_source": {
      "@timestamp": "2024-09-13T13:04:22.759Z",
      "message": "2024-09-13T13:04:16.916Z  INFO 1 --- [app1m] [http-nio-8081-exec-10] pt.obs.rest.AppRestController            : Calling API 1",
      "input": {
	"type": "filestream"
      },
      "ecs": {
	"version": "8.0.0"
      },
      "host": {
	"name": "5b73a6bd3b99"
      },
      "agent": {
	"name": "5b73a6bd3b99",
	"type": "filebeat",
	"version": "8.11.1",
	"ephemeral_id": "92dc00d5-4364-429a-9894-e33011187cb3",
	"id": "a0f97589-8208-4933-9389-c32bf0f7b2d1"
      },
      "log": {
	"offset": 63351,
	"file": {
	  "path": "/var/log/app_logs/app1m.log",
	  "device_id": "2080",
	  "inode": "6727840"
	}
      }
    },
    "fields": {
      "input.type": [
	"filestream"
      ],
      "log.offset": [
	63351
      ],
      "agent.hostname": [
	"5b73a6bd3b99"
      ],
      "message": [
	"2024-09-13T13:04:16.916Z  INFO 1 --- [app1m] [http-nio-8081-exec-10] pt.obs.rest.AppRestController            : Calling API 1"
      ],
      "agent.type": [
	"filebeat"
      ],
      "@timestamp": [
	"2024-09-13T13:04:22.759Z"
      ],
      "agent.id": [
	"a0f97589-8208-4933-9389-c32bf0f7b2d1"
      ],
      "ecs.version": [
	"8.0.0"
      ],
      "log.file.inode": [
	"6727840"
      ],
      "log.file.device_id": [
	"2080"
      ],
      "log.file.path": [
	"/var/log/app_logs/app1m.log"
      ],
      "agent.ephemeral_id": [
	"92dc00d5-4364-429a-9894-e33011187cb3"
      ],
      "agent.name": [
	"5b73a6bd3b99"
      ],
      "agent.version": [
	"8.11.1"
      ],
      "host.name": [
	"5b73a6bd3b99"
      ]
    }
  }
#+end_src

- Logs are only visible in log stream, but not in APM
- Logs have no trace id and are not seen and correllated with APM.

***** Errors
Generates multiple entries for one excpetion, because of linebreaks in stacktrace output:
| Field              | Value                                                                                                                                                                                                                                                                                                          |
|--------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| _id                | c6mg65EBkJCAMLR03E7p                                                                                                                                                                                                                                                                                           |
| _index             | .ds-filebeat-8.11.1-2024.09.13-000001                                                                                                                                                                                                                                                                          |
| _score             | -                                                                                                                                                                                                                                                                                                              |
| @timestamp         | Sep 13, 2024 @ 15:44:32.761                                                                                                                                                                                                                                                                                    |
| agent.ephemeral_id | 92dc00d5-4364-429a-9894-e33011187cb3                                                                                                                                                                                                                                                                           |
| agent.hostname     | 5b73a6bd3b99                                                                                                                                                                                                                                                                                                   |
| agent.id           | a0f97589-8208-4933-9389-c32bf0f7b2d1                                                                                                                                                                                                                                                                           |
| agent.name         | 5b73a6bd3b99                                                                                                                                                                                                                                                                                                   |
| agent.type         | filebeat                                                                                                                                                                                                                                                                                                       |
| agent.version      | 8.11.1                                                                                                                                                                                                                                                                                                         |
| ecs.version        | 8.0.0                                                                                                                                                                                                                                                                                                          |
| host.name          | 5b73a6bd3b99                                                                                                                                                                                                                                                                                                   |
| input.type         | filestream                                                                                                                                                                                                                                                                                                     |
| log.file.device_id | 2080                                                                                                                                                                                                                                                                                                           |
| log.file.inode     | 6727840                                                                                                                                                                                                                                                                                                        |
| log.file.path      | /var/log/app_logs/app1m.log                                                                                                                                                                                                                                                                                    |
| log.offset         | 68,684                                                                                                                                                                                                                                                                                                         |
| message            | 2024-09-13T13:44:23.483Z ERROR 1 --- [app1m] [http-nio-8081-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.RuntimeException: An unexpected error occurred] with root cause |

#+begin_src json
  {
    "_index": ".ds-filebeat-8.11.1-2024.09.13-000001",
    "_id": "c6mg65EBkJCAMLR03E7p",
    "_version": 1,
    "_score": 0,
    "_source": {
      "@timestamp": "2024-09-13T13:44:32.761Z",
      "log": {
	"offset": 68684,
	"file": {
	  "path": "/var/log/app_logs/app1m.log",
	  "device_id": "2080",
	  "inode": "6727840"
	}
      },
      "message": "2024-09-13T13:44:23.483Z ERROR 1 --- [app1m] [http-nio-8081-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.RuntimeException: An unexpected error occurred] with root cause",
      "input": {
	"type": "filestream"
      },
      "agent": {
	"ephemeral_id": "92dc00d5-4364-429a-9894-e33011187cb3",
	"id": "a0f97589-8208-4933-9389-c32bf0f7b2d1",
	"name": "5b73a6bd3b99",
	"type": "filebeat",
	"version": "8.11.1"
      },
      "ecs": {
	"version": "8.0.0"
      },
      "host": {
	"name": "5b73a6bd3b99"
      }
    },
    "fields": {
      "input.type": [
	"filestream"
      ],
      "log.offset": [
	68684
      ],
      "agent.hostname": [
	"5b73a6bd3b99"
      ],
      "message": [
	"2024-09-13T13:44:23.483Z ERROR 1 --- [app1m] [http-nio-8081-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.RuntimeException: An unexpected error occurred] with root cause"
      ],
      "agent.type": [
	"filebeat"
      ],
      "@timestamp": [
	"2024-09-13T13:44:32.761Z"
      ],
      "agent.id": [
	"a0f97589-8208-4933-9389-c32bf0f7b2d1"
      ],
      "ecs.version": [
	"8.0.0"
      ],
      "log.file.inode": [
	"6727840"
      ],
      "log.file.device_id": [
	"2080"
      ],
      "log.file.path": [
	"/var/log/app_logs/app1m.log"
      ],
      "agent.ephemeral_id": [
	"92dc00d5-4364-429a-9894-e33011187cb3"
      ],
      "agent.name": [
	"5b73a6bd3b99"
      ],
      "agent.version": [
	"8.11.1"
      ],
      "host.name": [
	"5b73a6bd3b99"
      ]
    }
  }
#+end_src

| Field              | Value                                                    |
|--------------------+----------------------------------------------------------|
| _id                | dKmg65EBkJCAMLR03E7p                                     |
| _index             | .ds-filebeat-8.11.1-2024.09.13-000001                    |
| _score             | -                                                        |
| @timestamp         | Sep 13, 2024 @ 15:44:32.761                              |
| agent.ephemeral_id | 92dc00d5-4364-429a-9894-e33011187cb3                     |
| agent.hostname     | 5b73a6bd3b99                                             |
| agent.id           | a0f97589-8208-4933-9389-c32bf0f7b2d1                     |
| agent.name         | 5b73a6bd3b99                                             |
| agent.type         | filebeat                                                 |
| agent.version      | 8.11.1                                                   |
| ecs.version        | 8.0.0                                                    |
| host.name          | 5b73a6bd3b99                                             |
| input.type         | filestream                                               |
| log.file.device_id | 2080                                                     |
| log.file.inode     | 6727840                                                  |
| log.file.path      | /var/log/app_logs/app1m.log                              |
| log.offset         | 68,988                                                   |
| message            | java.lang.RuntimeException: An unexpected error occurred |

#+begin_src json
  {
    "_index": ".ds-filebeat-8.11.1-2024.09.13-000001",
    "_id": "dKmg65EBkJCAMLR03E7p",
    "_version": 1,
    "_score": 0,
    "_source": {
      "@timestamp": "2024-09-13T13:44:32.761Z",
      "input": {
	"type": "filestream"
      },
      "ecs": {
	"version": "8.0.0"
      },
      "host": {
	"name": "5b73a6bd3b99"
      },
      "agent": {
	"id": "a0f97589-8208-4933-9389-c32bf0f7b2d1",
	"name": "5b73a6bd3b99",
	"type": "filebeat",
	"version": "8.11.1",
	"ephemeral_id": "92dc00d5-4364-429a-9894-e33011187cb3"
      },
      "log": {
	"offset": 68988,
	"file": {
	  "device_id": "2080",
	  "inode": "6727840",
	  "path": "/var/log/app_logs/app1m.log"
	}
      },
      "message": "java.lang.RuntimeException: An unexpected error occurred"
    },
    "fields": {
      "input.type": [
	"filestream"
      ],
      "log.offset": [
	68988
      ],
      "agent.hostname": [
	"5b73a6bd3b99"
      ],
      "message": [
	"java.lang.RuntimeException: An unexpected error occurred"
      ],
      "agent.type": [
	"filebeat"
      ],
      "@timestamp": [
	"2024-09-13T13:44:32.761Z"
      ],
      "agent.id": [
	"a0f97589-8208-4933-9389-c32bf0f7b2d1"
      ],
      "ecs.version": [
	"8.0.0"
      ],
      "log.file.inode": [
	"6727840"
      ],
      "log.file.device_id": [
	"2080"
      ],
      "log.file.path": [
	"/var/log/app_logs/app1m.log"
      ],
      "agent.ephemeral_id": [
	"92dc00d5-4364-429a-9894-e33011187cb3"
      ],
      "agent.name": [
	"5b73a6bd3b99"
      ],
      "agent.version": [
	"8.11.1"
      ],
      "host.name": [
	"5b73a6bd3b99"
      ]
    }
  }
#+end_src

There are no differences to normal info messages.

*** App2
Like App1, but
- Implements [[https://www.elastic.co/guide/en/ecs-logging/overview/current/intro.html][ECS Logging]] for logs, using [[https://www.elastic.co/guide/en/ecs-logging/java/1.x/setup.html][ECS Java logging]]
- Logs are written in the default format to stdout like in App1
- Logs are written in JSON format to a file, if application runs in a container. This saves filebeat resources, since it must not transform the logs into JSON and offers better filtering options in Elasticsearch and Kibana.
- Publish metrics using also [[https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.metrics.export.prometheus][Prometheus-Exporter]]. These metrics can be analysed in Kibana.
- Instrumented, using the [[https://www.elastic.co/guide/en/apm/agent/java/1.x/intro.html][APM Java Agent]]
- Writes messages to Kafka topic ~topic2~
- Reads messages from Kafka topic ~topic1~ and ~topic3~

**** APIs
***** Success
The following call writes a message to Kafka topic ~topic2~:
#+begin_src shell
  curl localhost:8182/api-1
#+end_src

***** Throwing unexpected errors / Stacktrace
#+begin_src shell
  curl localhost:8182/api-2
#+end_src

Calling this API will increase the metric ~prometheus.metrics.logback_events_total~

**** Metrics
Metrics are also available at the actuator Prometheus endpoint, e.g. for the ~api1Counter~:
#+begin_src shell :results replace verbatim :wrap example
  curl -s localhost:8182/actuator/prometheus | grep -e api_1
#+end_src

The result will be something like:
#+begin_example
  # HELP app2m_api_1_counter_total  
  # TYPE app2m_api_1_counter_total counter
  app2m_api_1_counter_total{it_1="it-2",type="FACHLICH",} 0.0
#+end_example

Since these metrics can be requested by a single URL, they can be collected with Metricbeat. The metrics can be analysed in Kibana, using the ~metricbeat-*~ stream. They are also accessible by APM.
The setting of ~management.endpoints.web.exposure.include~ determines, which metrics are shown, when calling the API:
#+begin_src shell :results replace raw :wrap src json
  curl -s localhost:8182/actuator/metrics
#+end_src

Difference between ~management.endpoints.web.exposure.include=info,health,metrics,prometheus~ and ~management.endpoints.web.exposure.include=*~ are, that the following metrics are only shown with the latter configuration:
#+begin_example
  http.server.requests
  kafka.consumer.node.incoming.byte.rate
  kafka.consumer.node.incoming.byte.total
  kafka.consumer.node.outgoing.byte.rate
  kafka.consumer.node.outgoing.byte.total
  kafka.consumer.node.request.latency.avg
  kafka.consumer.node.request.latency.max
  kafka.consumer.node.request.rate
  kafka.consumer.node.request.size.avg
  kafka.consumer.node.request.size.max
  kafka.consumer.node.request.total
  kafka.consumer.node.response.rate
  kafka.consumer.node.response.total
#+end_example

**** Traces
Traces are handled like in App1:
#+begin_src shell
  curl -H 'traceparent: 00-01020000000000000000000000000001-0000000000000001-01' localhost:8182/api-1
#+end_src

In Kibana ~trace.id~ and ~trace.parent~ can be verified at /Observability/ -> /APM/ -> /Services/ -> /app2m/ -> /Transactions/ -> /AppRestController#app2m/

****** Logs
Logs are structured and can be seen under APM.
In general this new 3 fields are added:

| Field               | Value                                                               |
|---------------------+---------------------------------------------------------------------|
| process.thread.name | main                                                                |
| service.name        | app2m                                                               |
| service.version     | 0.0.1-SNAPSHOT                                                      |

If a request sets a ~traceparent~-Header (e.g. by REST-calls or incoming Kafka-Messages). ~trace.id~ and ~transaction.id~ are added in the log message as well:

| Field               | Value                                |
|---------------------+--------------------------------------|
| trace.id            | 01020000000000000000000000000001     |
| transaction.id      | 0c2dd98069817f01                     |

With the ~trace.id~ the log messages can be correllated and seen under APM.

**** Logs
The following fields are set in the log messages:

| Field               | Value                                 |
|---------------------+---------------------------------------|
| _id                 | nKh865EBkJCAMLR0dFmY                  |
| _index              | .ds-filebeat-8.11.1-2024.09.13-000001 |
| _score              | -                                     |
| @timestamp          | Sep 13, 2024 @ 15:04:39.903           |
| agent.ephemeral_id  | 92dc00d5-4364-429a-9894-e33011187cb3  |
| agent.hostname      | 5b73a6bd3b99                          |
| agent.id            | a0f97589-8208-4933-9389-c32bf0f7b2d1  |
| agent.name          | 5b73a6bd3b99                          |
| agent.type          | filebeat                              |
| agent.version       | 8.11.1                                |
| ecs.version         | 1.2.0                                 |
| event.dataset       | app2m                                 |
| host.name           | 5b73a6bd3b99                          |
| input.type          | filestream                            |
| log.file.device_id  | 2080                                  |
| log.file.inode      | 6724123                               |
| log.file.path       | /var/log/app_logs/app2m.log.json      |
| log.level           | INFO                                  |
| log.logger          | pt.obs.rest.AppRestController         |
| log.offset          | 60,571                                |
| message             | Calling API 1                         |
| process.thread.name | http-nio-8082-exec-1                  |
| service.name        | app2m                                 |
| service.version     | 0.0.1-SNAPSHOT                        |
| trace.id            | c9cdd7e7b614e718bb628d53d2b6990c      |
| transaction.id      | 1e3407e395660010

#+begin_src json
  {
    "_index": ".ds-filebeat-8.11.1-2024.09.13-000001",
    "_id": "nKh865EBkJCAMLR0dFmY",
    "_version": 1,
    "_score": 0,
    "_source": {
      "@timestamp": "2024-09-13T13:04:39.903Z",
      "transaction": {
	"id": "1e3407e395660010"
      },
      "input": {
	"type": "filestream"
      },
      "host": {
	"name": "5b73a6bd3b99"
      },
      "trace": {
	"id": "c9cdd7e7b614e718bb628d53d2b6990c"
      },
      "process": {
	"thread": {
	  "name": "http-nio-8082-exec-1"
	}
      },
      "log": {
	"offset": 60571,
	"file": {
	  "inode": "6724123",
	  "path": "/var/log/app_logs/app2m.log.json",
	  "device_id": "2080"
	},
	"level": "INFO",
	"logger": "pt.obs.rest.AppRestController"
      },
      "message": "Calling API 1",
      "event": {
	"dataset": "app2m"
      },
      "agent": {
	"version": "8.11.1",
	"ephemeral_id": "92dc00d5-4364-429a-9894-e33011187cb3",
	"id": "a0f97589-8208-4933-9389-c32bf0f7b2d1",
	"name": "5b73a6bd3b99",
	"type": "filebeat"
      },
      "ecs": {
	"version": "1.2.0"
      },
      "service": {
	"name": "app2m",
	"version": "0.0.1-SNAPSHOT"
      }
    },
    "fields": {
      "service.name": [
	"app2m"
      ],
      "input.type": [
	"filestream"
      ],
      "log.offset": [
	60571
      ],
      "agent.hostname": [
	"5b73a6bd3b99"
      ],
      "message": [
	"Calling API 1"
      ],
      "log.logger": [
	"pt.obs.rest.AppRestController"
      ],
      "transaction.id": [
	"1e3407e395660010"
      ],
      "agent.type": [
	"filebeat"
      ],
      "trace.id": [
	"c9cdd7e7b614e718bb628d53d2b6990c"
      ],
      "@timestamp": [
	"2024-09-13T13:04:39.903Z"
      ],
      "agent.id": [
	"a0f97589-8208-4933-9389-c32bf0f7b2d1"
      ],
      "service.version": [
	"0.0.1-SNAPSHOT"
      ],
      "ecs.version": [
	"1.2.0"
      ],
      "log.file.inode": [
	"6724123"
      ],
      "log.file.device_id": [
	"2080"
      ],
      "log.file.path": [
	"/var/log/app_logs/app2m.log.json"
      ],
      "agent.ephemeral_id": [
	"92dc00d5-4364-429a-9894-e33011187cb3"
      ],
      "log.level": [
	"INFO"
      ],
      "agent.name": [
	"5b73a6bd3b99"
      ],
      "agent.version": [
	"8.11.1"
      ],
      "host.name": [
	"5b73a6bd3b99"
      ],
      "event.dataset": [
	"app2m"
      ],
      "process.thread.name": [
	"http-nio-8082-exec-1"
      ]
    }
  }
#+end_src

- ~ecs.version~ is set to 1.2.0
- New fields: ~event.dataset~, ~log.level~, ~log.logger~, ~process.thread.name~, ~service.name~, ~service.version~, ~trace.id~ and ~transaction.id~
- ~message~ is stripped
- Logs are only visible in log stream, but not in APM
- Logs have ~trace.id~ and are seen and correllated with APM.

***** Errors
https://www.elastic.co/guide/en/ecs/8.11/ecs-error.html
- ~error.message~ contains error message
- ~error.stack_trace~ contains full stack trace without linebreaks. So only one message per error exists.
- ~error.type~ contains exception
- No trace id set

| Field               | Value                                                                                                                                                                                           |
|---------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| _id                 | iqmh65EBkJCAMLR0A0_y                                                                                                                                                                            |
| _index              | .ds-filebeat-8.11.1-2024.09.13-000001                                                                                                                                                           |
| _score              | -                                                                                                                                                                                               |
| @timestamp          | Sep 13, 2024 @ 15:44:41.803                                                                                                                                                                     |
| agent.ephemeral_id  | 92dc00d5-4364-429a-9894-e33011187cb3                                                                                                                                                            |
| agent.hostname      | 5b73a6bd3b99                                                                                                                                                                                    |
| agent.id            | a0f97589-8208-4933-9389-c32bf0f7b2d1                                                                                                                                                            |
| agent.name          | 5b73a6bd3b99                                                                                                                                                                                    |
| agent.type          | filebeat                                                                                                                                                                                        |
| agent.version       | 8.11.1                                                                                                                                                                                          |
| ecs.version         | 1.2.0                                                                                                                                                                                           |
| error.message       | An unexpected error occurred                                                                                                                                                                    |
| error.stack_trace   | java.lang.RuntimeException: An unexpected error occurred                                                                                                                                        |
|                     | at ...                                                                                                                                                                                          |
| error.type          | java.lang.RuntimeException                                                                                                                                                                      |
| event.dataset       | app2m                                                                                                                                                                                           |
| host.name           | 5b73a6bd3b99                                                                                                                                                                                    |
| input.type          | filestream                                                                                                                                                                                      |
| log.file.device_id  | 2080                                                                                                                                                                                            |
| log.file.inode      | 6724123                                                                                                                                                                                         |
| log.file.path       | /var/log/app_logs/app2m.log.json                                                                                                                                                                |
| log.level           | ERROR                                                                                                                                                                                           |
| log.logger          | org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]                                                                                                             |
| log.offset          | 68,421                                                                                                                                                                                          |
| message             | Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.RuntimeException: An unexpected error occurred] with root cause |
| process.thread.name | http-nio-8082-exec-5                                                                                                                                                                            |
| service.name        | app2m                                                                                                                                                                                           |
| service.version     | 0.0.1-SNAPSHOT

#+begin_src json
  {
    "_index": ".ds-filebeat-8.11.1-2024.09.13-000001",
    "_id": "iqmh65EBkJCAMLR0A0_y",
    "_version": 1,
    "_score": 0,
    "_source": {
      "@timestamp": "2024-09-13T13:44:41.803Z",
      "service": {
	"name": "app2m",
	"version": "0.0.1-SNAPSHOT"
      },
      "process": {
	"thread": {
	  "name": "http-nio-8082-exec-5"
	}
      },
      "input": {
	"type": "filestream"
      },
      "host": {
	"name": "5b73a6bd3b99"
      },
      "ecs": {
	"version": "1.2.0"
      },
      "event": {
	"dataset": "app2m"
      },
      "error": {
	"stack_trace": "java.lang.RuntimeException: An unexpected error occurred\n\tat pt.obs.rest.AppRestController.api2(AppRestController.java:54)\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)\n\tat java.base/java.lang.reflect.Method.invoke(Unknown Source)\n\tat org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:262)\n\tat org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:190)\n\tat org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)\n\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:917)\n\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:829)\n\tat org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)\n\tat org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)\n\tat org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)\n\tat org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)\n\tat org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)\n\tat jakarta.servlet.http.HttpServlet.service(HttpServlet.java:564)\n\tat org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)\n\tat jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)\n\tat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)\n\tat org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)\n\tat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)\n\tat org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)\n\tat org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)\n\tat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340)\n\tat org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)\n\tat org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)\n\tat org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)\n\tat org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)\n\tat org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)\n\tat org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)\n\tat org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)\n\tat org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\n\tat java.base/java.lang.Thread.run(Unknown Source)\n",
	"type": "java.lang.RuntimeException",
	"message": "An unexpected error occurred"
      },
      "log": {
	"offset": 68421,
	"file": {
	  "path": "/var/log/app_logs/app2m.log.json",
	  "device_id": "2080",
	  "inode": "6724123"
	},
	"logger": "org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]",
	"level": "ERROR"
      },
      "agent": {
	"ephemeral_id": "92dc00d5-4364-429a-9894-e33011187cb3",
	"id": "a0f97589-8208-4933-9389-c32bf0f7b2d1",
	"name": "5b73a6bd3b99",
	"type": "filebeat",
	"version": "8.11.1"
      },
      "message": "Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.RuntimeException: An unexpected error occurred] with root cause"
    },
    "fields": {
      "log.logger": [
	"org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]"
      ],
      "agent.type": [
	"filebeat"
      ],
      "log.file.device_id": [
	"2080"
      ],
      "log.level": [
	"ERROR"
      ],
      "agent.name": [
	"5b73a6bd3b99"
      ],
      "host.name": [
	"5b73a6bd3b99"
      ],
      "process.thread.name": [
	"http-nio-8082-exec-5"
      ],
      "service.name": [
	"app2m"
      ],
      "input.type": [
	"filestream"
      ],
      "log.offset": [
	68421
      ],
      "agent.hostname": [
	"5b73a6bd3b99"
      ],
      "message": [
	"Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.RuntimeException: An unexpected error occurred] with root cause"
      ],
      "@timestamp": [
	"2024-09-13T13:44:41.803Z"
      ],
      "error.type": [
	"java.lang.RuntimeException"
      ],
      "agent.id": [
	"a0f97589-8208-4933-9389-c32bf0f7b2d1"
      ],
      "service.version": [
	"0.0.1-SNAPSHOT"
      ],
      "ecs.version": [
	"1.2.0"
      ],
      "error.message": [
	"An unexpected error occurred"
      ],
      "log.file.inode": [
	"6724123"
      ],
      "log.file.path": [
	"/var/log/app_logs/app2m.log.json"
      ],
      "agent.ephemeral_id": [
	"92dc00d5-4364-429a-9894-e33011187cb3"
      ],
      "agent.version": [
	"8.11.1"
      ],
      "error.stack_trace": [
	"java.lang.RuntimeException: An unexpected error occurred\n\tat pt.obs.rest.AppRestController.api2(AppRestController.java:54)\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)\n\tat java.base/java.lang.reflect.Method.invoke(Unknown Source)\n\tat org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:262)\n\tat org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:190)\n\tat org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)\n\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:917)\n\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:829)\n\tat org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)\n\tat org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)\n\tat org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)\n\tat org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)\n\tat org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)\n\tat jakarta.servlet.http.HttpServlet.service(HttpServlet.java:564)\n\tat org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)\n\tat jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)\n\tat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)\n\tat org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)\n\tat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)\n\tat org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)\n\tat org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)\n\tat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340)\n\tat org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)\n\tat org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)\n\tat org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)\n\tat org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)\n\tat org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)\n\tat org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)\n\tat org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)\n\tat org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\n\tat java.base/java.lang.Thread.run(Unknown Source)\n"
      ],
      "error.stack_trace.text": [
	"java.lang.RuntimeException: An unexpected error occurred\n\tat pt.obs.rest.AppRestController.api2(AppRestController.java:54)\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)\n\tat java.base/java.lang.reflect.Method.invoke(Unknown Source)\n\tat org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:262)\n\tat org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:190)\n\tat org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)\n\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:917)\n\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:829)\n\tat org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)\n\tat org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)\n\tat org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)\n\tat org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)\n\tat org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)\n\tat jakarta.servlet.http.HttpServlet.service(HttpServlet.java:564)\n\tat org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)\n\tat jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)\n\tat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)\n\tat org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)\n\tat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)\n\tat org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)\n\tat org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)\n\tat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340)\n\tat org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)\n\tat org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)\n\tat org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)\n\tat org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)\n\tat org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)\n\tat org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)\n\tat org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)\n\tat org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\n\tat java.base/java.lang.Thread.run(Unknown Source)\n"
      ],
      "event.dataset": [
	"app2m"
      ]
    }
  }
#+end_src

*** App3
Like App2, but
- Publish metrics using [[https://opentelemetry.io/docs/instrumentation/java/automatic/][Automatic Instrumentation]] with an [[https://www.elastic.co/guide/en/apm/guide/current/open-telemetry-direct.html#instrument-apps-otel][OpenTelemetry Agent]] instead of an APM Java Agent or exporting the metrics with an [[https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.metrics.export.otlp][OpenTelemetry-Exporter]]. 
- Not using Prometheus
- Using deployment pattern [[https://opentelemetry.io/docs/collector/deployment/no-collector/][No Collector]] to ship metrics directly to APM
- Writes messages to Kafka topic ~topic3~
- Reads messages from Kafka topic ~topic1~ and ~topic2~
  
**** APIs
***** Success
The following call writes a message to Kafka topic ~topic3~:
#+begin_src shell
  curl localhost:8183/api-1
#+end_src

***** Throwing unexpected errors / Stacktrace
#+begin_src shell
  curl localhost:8183/api-2
#+end_src
To analyse otel behaviour, start the application with ~Ddebug~.

**** Metrics
Metrics are partially handled like in App1, but not transferred to Elasticsearch and even not visible in APM.
Metrics are only available at the actuator endpoint, e.g. for the ~api1Counter~:
#+begin_src shell :results replace raw :wrap example json
   curl localhost:8183/actuator/metrics/app3m.api-1.counter
#+end_src

The output will be something like:
#+begin_example json
{"name":"app3m.api-1.counter","measurements":[{"statistic":"COUNT","value":0.0}],"availableTags":[{"tag":"type","values":["FACHLICH"]},{"tag":"it-1","values":["it-2"]}]}
#+end_example

If no measurement is shown, like in the following example, the app has to be restarted:
#+begin_example json
{"name":"app3m.api-1.counter","measurements":[],"availableTags":[{"tag":"type","values":["FACHLICH"]},{"tag":"it-1","values":["it-2"]}]}
#+end_example

**** Traces
Traces have less information as in App1 or App2 (e.g. only ~http.request.method~ and ~http.response.status_code~, but contain also ~parent.id~ and ~trace.id~. Only ~traceparent~ header is set in Kafka headers.
#+begin_src shell
  curl -H 'traceparent: 00-01030000000000000000000000000001-0000000000000001-01' localhost:8183/api-1
#+end_src

**** Logs
Like in App2, logs are structured and can be seen under APM. They are visible and can be correllated in APM. They have no ~trace.id~ or ~span.id~ but a ~trace_id~ and a ~span_id~. Additional a ~trace_flags~ is set, which shows the flags set in the ~traceparent~ W3C header. They have no field No ~service.version~:

| Field               | Value                                 |
|---------------------+---------------------------------------|
| _id                 | vah865EBkJCAMLR0m1qr                  |
| _index              | .ds-filebeat-8.11.1-2024.09.13-000001 |
| _score              | -                                     |
| @timestamp          | Sep 13, 2024 @ 15:04:51.633           |
| agent.ephemeral_id  | 92dc00d5-4364-429a-9894-e33011187cb3  |
| agent.hostname      | 5b73a6bd3b99                          |
| agent.id            | a0f97589-8208-4933-9389-c32bf0f7b2d1  |
| agent.name          | 5b73a6bd3b99                          |
| agent.type          | filebeat                              |
| agent.version       | 8.11.1                                |
| ecs.version         | 1.2.0                                 |
| event.dataset       | app3m                                 |
| host.name           | 5b73a6bd3b99                          |
| input.type          | filestream                            |
| log.file.device_id  | 2080                                  |
| log.file.inode      | 6740395                               |
| log.file.path       | /var/log/app_logs/app3m.log.json      |
| log.level           | INFO                                  |
| log.logger          | pt.obs.rest.AppRestController         |
| log.offset          | 23,887                                |
| message             | Calling API 1                         |
| process.thread.name | http-nio-8083-exec-4                  |
| service.name        | app3m                                 |
| span_id             | 9efe3447eb4d674a                      |
| trace_flags         | 01                                    |
| trace_id            | 5e7b333ff00469f84c22e3a009e07349      |

#+begin_src json
  {
    "_index": ".ds-filebeat-8.11.1-2024.09.13-000001",
    "_id": "vah865EBkJCAMLR0m1qr",
    "_version": 1,
    "_score": 0,
    "_source": {
      "@timestamp": "2024-09-13T13:04:51.633Z",
      "host": {
	"name": "5b73a6bd3b99"
      },
      "agent": {
	"name": "5b73a6bd3b99",
	"type": "filebeat",
	"version": "8.11.1",
	"ephemeral_id": "92dc00d5-4364-429a-9894-e33011187cb3",
	"id": "a0f97589-8208-4933-9389-c32bf0f7b2d1"
      },
      "trace_flags": "01",
      "ecs": {
	"version": "1.2.0"
      },
      "span_id": "9efe3447eb4d674a",
      "trace_id": "5e7b333ff00469f84c22e3a009e07349",
      "input": {
	"type": "filestream"
      },
      "message": "Calling API 1",
      "service": {
	"name": "app3m"
      },
      "process": {
	"thread": {
	  "name": "http-nio-8083-exec-4"
	}
      },
      "log": {
	"logger": "pt.obs.rest.AppRestController",
	"offset": 23887,
	"file": {
	  "path": "/var/log/app_logs/app3m.log.json",
	  "device_id": "2080",
	  "inode": "6740395"
	},
	"level": "INFO"
      },
      "event": {
	"dataset": "app3m"
      }
    },
    "fields": {
      "trace_id": [
	"5e7b333ff00469f84c22e3a009e07349"
      ],
      "service.name": [
	"app3m"
      ],
      "span_id": [
	"9efe3447eb4d674a"
      ],
      "input.type": [
	"filestream"
      ],
      "log.offset": [
	23887
      ],
      "agent.hostname": [
	"5b73a6bd3b99"
      ],
      "message": [
	"Calling API 1"
      ],
      "log.logger": [
	"pt.obs.rest.AppRestController"
      ],
      "agent.type": [
	"filebeat"
      ],
      "@timestamp": [
	"2024-09-13T13:04:51.633Z"
      ],
      "agent.id": [
	"a0f97589-8208-4933-9389-c32bf0f7b2d1"
      ],
      "trace_flags": [
	"01"
      ],
      "ecs.version": [
	"1.2.0"
      ],
      "log.file.inode": [
	"6740395"
      ],
      "log.file.device_id": [
	"2080"
      ],
      "log.file.path": [
	"/var/log/app_logs/app3m.log.json"
      ],
      "agent.ephemeral_id": [
	"92dc00d5-4364-429a-9894-e33011187cb3"
      ],
      "log.level": [
	"INFO"
      ],
      "agent.name": [
	"5b73a6bd3b99"
      ],
      "agent.version": [
	"8.11.1"
      ],
      "host.name": [
	"5b73a6bd3b99"
      ],
      "event.dataset": [
	"app3m"
      ],
      "process.thread.name": [
	"http-nio-8083-exec-4"
      ]
    }
  }
#+end_src

***** Errors
Like in App2 ~error.message~, ~error.stack_trace~ and ~error.type~ are set. Additionally ~span_id~, ~trace_flags~ and ~trace_id~ are set:

| Field               | Value                                                                                                                                                                                           |
|---------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| _id                 | Damh65EBkJCAMLR0oFQ0                                                                                                                                                                            |
| _index              | .ds-filebeat-8.11.1-2024.09.13-000001                                                                                                                                                           |
| _score              | -                                                                                                                                                                                               |
| @timestamp          | Sep 13, 2024 @ 15:45:14.567                                                                                                                                                                     |
| agent.ephemeral_id  | 92dc00d5-4364-429a-9894-e33011187cb3                                                                                                                                                            |
| agent.hostname      | 5b73a6bd3b99                                                                                                                                                                                    |
| agent.id            | a0f97589-8208-4933-9389-c32bf0f7b2d1                                                                                                                                                            |
| agent.name          | 5b73a6bd3b99                                                                                                                                                                                    |
| agent.type          | filebeat                                                                                                                                                                                        |
| agent.version       | 8.11.1                                                                                                                                                                                          |
| ecs.version         | 1.2.0                                                                                                                                                                                           |
| error.message       | An unexpected error occurred                                                                                                                                                                    |
| error.stack_trace   | java.lang.RuntimeException: An unexpected error occurred                                                                                                                                        |
|                     | at ...                                                                                                                                                                                          |
| error.type          | java.lang.RuntimeException                                                                                                                                                                      |
| event.dataset       | app3m                                                                                                                                                                                           |
| host.name           | 5b73a6bd3b99                                                                                                                                                                                    |
| input.type          | filestream                                                                                                                                                                                      |
| log.file.device_id  | 2080                                                                                                                                                                                            |
| log.file.inode      | 6740395                                                                                                                                                                                         |
| log.file.path       | /var/log/app_logs/app3m.log.json                                                                                                                                                                |
| log.level           | ERROR                                                                                                                                                                                           |
| log.logger          | org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]                                                                                                             |
| log.offset          | 39,622                                                                                                                                                                                          |
| message             | Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.RuntimeException: An unexpected error occurred] with root cause |
| process.thread.name | http-nio-8083-exec-9                                                                                                                                                                            |
| service.name        | app3m                                                                                                                                                                                           |
| span_id             | 7340054ef8a6e760                                                                                                                                                                                |
| trace_flags         | 01                                                                                                                                                                                              |
| trace_id            | 6c3b1d3e99957ca5b7cc7657d5d942e9                                                                                                                                                                |

#+begin_src json
  {
    "_index": ".ds-filebeat-8.11.1-2024.09.13-000001",
    "_id": "Damh65EBkJCAMLR0oFQ0",
    "_version": 1,
    "_score": 0,
    "_source": {
      "@timestamp": "2024-09-13T13:45:14.567Z",
      "trace_flags": "01",
      "ecs": {
	"version": "1.2.0"
      },
      "log": {
	"level": "ERROR",
	"logger": "org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]",
	"offset": 39622,
	"file": {
	  "path": "/var/log/app_logs/app3m.log.json",
	  "device_id": "2080",
	  "inode": "6740395"
	}
      },
      "process": {
	"thread": {
	  "name": "http-nio-8083-exec-9"
	}
      },
      "event": {
	"dataset": "app3m"
      },
      "error": {
	"stack_trace": "java.lang.RuntimeException: An unexpected error occurred\n\tat pt.obs.rest.AppRestController.api2(AppRestController.java:54)\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)\n\tat java.base/java.lang.reflect.Method.invoke(Unknown Source)\n\tat org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:262)\n\tat org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:190)\n\tat org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)\n\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:917)\n\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:829)\n\tat org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)\n\tat org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)\n\tat org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)\n\tat org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)\n\tat org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)\n\tat jakarta.servlet.http.HttpServlet.service(HttpServlet.java:564)\n\tat org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)\n\tat jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.springframework.web.servlet.v6_0.OpenTelemetryHandlerMappingFilter.doFilter(OpenTelemetryHandlerMappingFilter.java:76)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)\n\tat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)\n\tat org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)\n\tat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)\n\tat org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)\n\tat org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)\n\tat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340)\n\tat org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)\n\tat org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)\n\tat org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)\n\tat org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)\n\tat org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)\n\tat org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)\n\tat org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)\n\tat org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\n\tat java.base/java.lang.Thread.run(Unknown Source)\n",
	"message": "An unexpected error occurred",
	"type": "java.lang.RuntimeException"
      },
      "input": {
	"type": "filestream"
      },
      "agent": {
	"id": "a0f97589-8208-4933-9389-c32bf0f7b2d1",
	"name": "5b73a6bd3b99",
	"type": "filebeat",
	"version": "8.11.1",
	"ephemeral_id": "92dc00d5-4364-429a-9894-e33011187cb3"
      },
      "trace_id": "6c3b1d3e99957ca5b7cc7657d5d942e9",
      "service": {
	"name": "app3m"
      },
      "message": "Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.RuntimeException: An unexpected error occurred] with root cause",
      "span_id": "7340054ef8a6e760",
      "host": {
	"name": "5b73a6bd3b99"
      }
    },
    "fields": {
      "log.logger": [
	"org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]"
      ],
      "agent.type": [
	"filebeat"
      ],
      "trace_flags": [
	"01"
      ],
      "log.file.device_id": [
	"2080"
      ],
      "log.level": [
	"ERROR"
      ],
      "agent.name": [
	"5b73a6bd3b99"
      ],
      "host.name": [
	"5b73a6bd3b99"
      ],
      "process.thread.name": [
	"http-nio-8083-exec-9"
      ],
      "trace_id": [
	"6c3b1d3e99957ca5b7cc7657d5d942e9"
      ],
      "service.name": [
	"app3m"
      ],
      "span_id": [
	"7340054ef8a6e760"
      ],
      "input.type": [
	"filestream"
      ],
      "log.offset": [
	39622
      ],
      "agent.hostname": [
	"5b73a6bd3b99"
      ],
      "message": [
	"Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.RuntimeException: An unexpected error occurred] with root cause"
      ],
      "@timestamp": [
	"2024-09-13T13:45:14.567Z"
      ],
      "error.type": [
	"java.lang.RuntimeException"
      ],
      "agent.id": [
	"a0f97589-8208-4933-9389-c32bf0f7b2d1"
      ],
      "ecs.version": [
	"1.2.0"
      ],
      "error.message": [
	"An unexpected error occurred"
      ],
      "log.file.inode": [
	"6740395"
      ],
      "log.file.path": [
	"/var/log/app_logs/app3m.log.json"
      ],
      "agent.ephemeral_id": [
	"92dc00d5-4364-429a-9894-e33011187cb3"
      ],
      "agent.version": [
	"8.11.1"
      ],
      "error.stack_trace": [
	"java.lang.RuntimeException: An unexpected error occurred\n\tat pt.obs.rest.AppRestController.api2(AppRestController.java:54)\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)\n\tat java.base/java.lang.reflect.Method.invoke(Unknown Source)\n\tat org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:262)\n\tat org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:190)\n\tat org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)\n\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:917)\n\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:829)\n\tat org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)\n\tat org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)\n\tat org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)\n\tat org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)\n\tat org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)\n\tat jakarta.servlet.http.HttpServlet.service(HttpServlet.java:564)\n\tat org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)\n\tat jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.springframework.web.servlet.v6_0.OpenTelemetryHandlerMappingFilter.doFilter(OpenTelemetryHandlerMappingFilter.java:76)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)\n\tat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)\n\tat org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)\n\tat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)\n\tat org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)\n\tat org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)\n\tat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340)\n\tat org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)\n\tat org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)\n\tat org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)\n\tat org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)\n\tat org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)\n\tat org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)\n\tat org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)\n\tat org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\n\tat java.base/java.lang.Thread.run(Unknown Source)\n"
      ],
      "error.stack_trace.text": [
	"java.lang.RuntimeException: An unexpected error occurred\n\tat pt.obs.rest.AppRestController.api2(AppRestController.java:54)\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)\n\tat java.base/java.lang.reflect.Method.invoke(Unknown Source)\n\tat org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:262)\n\tat org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:190)\n\tat org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)\n\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:917)\n\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:829)\n\tat org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)\n\tat org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)\n\tat org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)\n\tat org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)\n\tat org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)\n\tat jakarta.servlet.http.HttpServlet.service(HttpServlet.java:564)\n\tat org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)\n\tat jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.springframework.web.servlet.v6_0.OpenTelemetryHandlerMappingFilter.doFilter(OpenTelemetryHandlerMappingFilter.java:76)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)\n\tat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)\n\tat org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)\n\tat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)\n\tat org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)\n\tat org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)\n\tat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340)\n\tat org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)\n\tat org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)\n\tat org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)\n\tat org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)\n\tat org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)\n\tat org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)\n\tat org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)\n\tat org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\n\tat java.base/java.lang.Thread.run(Unknown Source)\n"
      ],
      "event.dataset": [
	"app3m"
      ]
    }
  }
#+end_src

*** App4
A simple Go application:
- Implements [[https://www.elastic.co/guide/en/ecs-logging/overview/current/intro.html][ECS Logging]] for logs, using [[https://www.elastic.co/guide/en/ecs-logging/go-logrus/current/setup.html][ECS Logging with logrus]]
- Logs are written in the default format to stdout like in App1 and to a file in ECS JSON format.
- Many fields are not set like in Java-Applications. Therefore at least the fields ~service.name~ and ~event.dataset~ are added. Further fields from [[https://www.elastic.co/guide/en/ecs-logging/java/current/setup.html][Java-Setup]] might be added
- Metrics are implemented, using [[https://prometheus.io/docs/guides/go-application/][Prometheus instrumentation]]
- The [[https://opentelemetry.io/docs/zero-code/go/][Go zero-code instrumentation]] did not work, so the [[https://opentelemetry.io/docs/languages/go/instrumentation/][manual instrumentation]] based on the [[https://opentelemetry.io/docs/languages/go/getting-started/][Getting Started guide]] is used

**** APIs
***** Success
The following call writes a message to Kafka topic ~topic4~:
#+begin_src shell
  curl localhost:8184/api-1
#+end_src

***** Throwing unexpected errors / Stacktrace
#+begin_src shell
  curl localhost:8184/api-2
#+end_src

**** Metrics
Metrics are also available at the actuator Prometheus endpoint, e.g. for the ~api1Counter~:
#+begin_src shell :results replace verbatim :wrap example
  curl -s localhost:8184/actuator/prometheus | grep app4
#+end_src

The result should be something like
#+begin_example
  # HELP app4m_api_1_counter 
  # TYPE app4m_api_1_counter counter
  app4m_api_1_counter{it_1="it-2"} 0
  # HELP app4m_api_2_counter 
  # TYPE app4m_api_2_counter counter
  app4m_api_2_counter{it_1="it-2"} 0
  # HELP app4m_api_3_counter 
  # TYPE app4m_api_3_counter counter
  app4m_api_3_counter{it_1="it-2"} 0
  # HELP app4m_topic_out_counter 
  # TYPE app4m_topic_out_counter counter
  app4m_topic_out_counter{it_1="it-2"} 0
#+end_example

Since these metrics are presented all at once, they can be collected with Metricbeat and analysed in Kibana, using the ~metricbeat-*~ stream.

**** TODO Traces
#+begin_src shell
  curl -H 'traceparent: 00-01040000000000000000000000000001-0000000000000001-01' localhost:8184/api-1
#+end_src

**** Logs
Logs are structured, like in App2. They have no ~trace.id~. The only ECS specific fields, which are added automatically are ~@timestamp~, ~ecs.version~, ~log.level~ and ~message~:

| Field              | Value                                 |
|--------------------+---------------------------------------|
| _id                | 7qh865EBkJCAMLR02lwj                  |
| _index             | .ds-filebeat-8.11.1-2024.09.13-000001 |
| _score             | -                                     |
| @timestamp         | Sep 13, 2024 @ 15:05:08.821           |
| agent.ephemeral_id | 92dc00d5-4364-429a-9894-e33011187cb3  |
| agent.hostname     | 5b73a6bd3b99                          |
| agent.id           | a0f97589-8208-4933-9389-c32bf0f7b2d1  |
| agent.name         | 5b73a6bd3b99                          |
| agent.type         | filebeat                              |
| agent.version      | 8.11.1                                |
| ecs.version        | 1.6.0                                 |
| event.dataset      | app4m                                 |
| host.name          | 5b73a6bd3b99                          |
| input.type         | filestream                            |
| log.file.device_id | 2080                                  |
| log.file.inode     | 6740979                               |
| log.file.path      | /var/log/app_logs/app4m.log.json      |
| log.level          | info                                  |
| log.offset         | 370                                   |
| message            | Calling API 1                         |
| service.name       | app4m                                 |

#+begin_src json
  {
    "_index": ".ds-filebeat-8.11.1-2024.09.13-000001",
    "_id": "7qh865EBkJCAMLR02lwj",
    "_version": 1,
    "_score": 0,
    "_source": {
      "@timestamp": "2024-09-13T13:05:08.821Z",
      "ecs": {
	"version": "1.6.0"
      },
      "input": {
	"type": "filestream"
      },
      "host": {
	"name": "5b73a6bd3b99"
      },
      "agent": {
	"id": "a0f97589-8208-4933-9389-c32bf0f7b2d1",
	"name": "5b73a6bd3b99",
	"type": "filebeat",
	"version": "8.11.1",
	"ephemeral_id": "92dc00d5-4364-429a-9894-e33011187cb3"
      },
      "event": {
	"dataset": "app4m"
      },
      "message": "Calling API 1",
      "log": {
	"offset": 370,
	"file": {
	  "device_id": "2080",
	  "inode": "6740979",
	  "path": "/var/log/app_logs/app4m.log.json"
	},
	"level": "info"
      },
      "service": {
	"name": "app4m"
      }
    },
    "fields": {
      "service.name": [
	"app4m"
      ],
      "input.type": [
	"filestream"
      ],
      "log.offset": [
	370
      ],
      "agent.hostname": [
	"5b73a6bd3b99"
      ],
      "message": [
	"Calling API 1"
      ],
      "agent.type": [
	"filebeat"
      ],
      "@timestamp": [
	"2024-09-13T13:05:08.821Z"
      ],
      "agent.id": [
	"a0f97589-8208-4933-9389-c32bf0f7b2d1"
      ],
      "ecs.version": [
	"1.6.0"
      ],
      "log.file.inode": [
	"6740979"
      ],
      "log.file.device_id": [
	"2080"
      ],
      "log.file.path": [
	"/var/log/app_logs/app4m.log.json"
      ],
      "agent.ephemeral_id": [
	"92dc00d5-4364-429a-9894-e33011187cb3"
      ],
      "log.level": [
	"info"
      ],
      "agent.name": [
	"5b73a6bd3b99"
      ],
      "agent.version": [
	"8.11.1"
      ],
      "host.name": [
	"5b73a6bd3b99"
      ],
      "event.dataset": [
	"app4m"
      ]
    }
  }
#+end_src

Further fields, like ~service.name~ or ~event.dataset~ had to be added as custom fields:
| Field              | Value                                  |
|--------------------+----------------------------------------|
| event.dataset      | app4                                   |
| service.name       | app4

They are not visible in APM, since no APM connection exists and no data is in the ~apm~ indices.

***** Errors
Following additional fields ~log.origin.file.line~, ~log.origin.file.name~ and ~log.origin.function~ (see: https://www.elastic.co/guide/en/ecs/8.11/ecs-log.html) are set:

| Field                | Value                                                                             |
|----------------------+-----------------------------------------------------------------------------------|
| _id                  | v6mh65EBkJCAMLR07lVT                                                              |
| _index               | .ds-filebeat-8.11.1-2024.09.13-000001                                             |
| _score               | -                                                                                 |
| @timestamp           | Sep 13, 2024 @ 15:45:38.341                                                       |
| agent.ephemeral_id   | 92dc00d5-4364-429a-9894-e33011187cb3                                              |
| agent.hostname       | 5b73a6bd3b99                                                                      |
| agent.id             | a0f97589-8208-4933-9389-c32bf0f7b2d1                                              |
| agent.name           | 5b73a6bd3b99                                                                      |
| agent.type           | filebeat                                                                          |
| agent.version        | 8.11.1                                                                            |
| ecs.version          | 1.6.0                                                                             |
| event.dataset        | app4m                                                                             |
| host.name            | 5b73a6bd3b99                                                                      |
| input.type           | filestream                                                                        |
| log.file.device_id   | 2080                                                                              |
| log.file.inode       | 6740979                                                                           |
| log.file.path        | /var/log/app_logs/app4m.log.json                                                  |
| log.level            | error                                                                             |
| log.offset           | 853                                                                               |
| log.origin.file.line | 60                                                                                |
| log.origin.file.name | /home/kunde/work/pt-observability-elastic/apps/app4/internal/logging/AppLogger.go |
| log.origin.function  | pt.observability.elastic/app4/internal/logging.Error                              |
| message              | An unexpected error occurred                                                      |
| service.name         | app4m

#+begin_src json
  {
    "_index": ".ds-filebeat-8.11.1-2024.09.13-000001",
    "_id": "v6mh65EBkJCAMLR07lVT",
    "_version": 1,
    "_score": 0,
    "_source": {
      "@timestamp": "2024-09-13T13:45:38.341Z",
      "service": {
	"name": "app4m"
      },
      "input": {
	"type": "filestream"
      },
      "host": {
	"name": "5b73a6bd3b99"
      },
      "agent": {
	"name": "5b73a6bd3b99",
	"type": "filebeat",
	"version": "8.11.1",
	"ephemeral_id": "92dc00d5-4364-429a-9894-e33011187cb3",
	"id": "a0f97589-8208-4933-9389-c32bf0f7b2d1"
      },
      "log": {
	"file": {
	  "path": "/var/log/app_logs/app4m.log.json",
	  "device_id": "2080",
	  "inode": "6740979"
	},
	"origin": {
	  "function": "pt.observability.elastic/app4/internal/logging.Error",
	  "file": {
	    "line": 60,
	    "name": "/home/kunde/work/pt-observability-elastic/apps/app4/internal/logging/AppLogger.go"
	  }
	},
	"level": "error",
	"offset": 853
      },
      "event": {
	"dataset": "app4m"
      },
      "message": "An unexpected error occurred",
      "ecs": {
	"version": "1.6.0"
      }
    },
    "fields": {
      "log.origin.file.line": [
	60
      ],
      "service.name": [
	"app4m"
      ],
      "input.type": [
	"filestream"
      ],
      "log.offset": [
	853
      ],
      "agent.hostname": [
	"5b73a6bd3b99"
      ],
      "message": [
	"An unexpected error occurred"
      ],
      "agent.type": [
	"filebeat"
      ],
      "@timestamp": [
	"2024-09-13T13:45:38.341Z"
      ],
      "log.origin.file.name": [
	"/home/kunde/work/pt-observability-elastic/apps/app4/internal/logging/AppLogger.go"
      ],
      "log.origin.function": [
	"pt.observability.elastic/app4/internal/logging.Error"
      ],
      "agent.id": [
	"a0f97589-8208-4933-9389-c32bf0f7b2d1"
      ],
      "ecs.version": [
	"1.6.0"
      ],
      "log.file.inode": [
	"6740979"
      ],
      "log.file.device_id": [
	"2080"
      ],
      "log.file.path": [
	"/var/log/app_logs/app4m.log.json"
      ],
      "agent.ephemeral_id": [
	"92dc00d5-4364-429a-9894-e33011187cb3"
      ],
      "log.level": [
	"error"
      ],
      "agent.name": [
	"5b73a6bd3b99"
      ],
      "agent.version": [
	"8.11.1"
      ],
      "host.name": [
	"5b73a6bd3b99"
      ],
      "event.dataset": [
	"app4m"
      ]
    }
  }
#+end_src
