/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pt.obs;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class AppTest {

    @Test
    void context_should_load() {}
}
